# Dockerfile para o Frontend Next.js 14
FROM node:18-slim

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

# Em prod o Next.js roda o build
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
